services:
  db:
    image: postgres:15-alpine
    container_name: lavapro-db
    restart: always
    env_file:
      - /opt/novatech-solutions/despliegue/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/ubuntu/backend/app/sql/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql
    networks:
      - lavapro_network

  backend:
    container_name: lavapro-backend
    restart: always
    build:
      context: /home/ubuntu/backend
      dockerfile: Dockerfile
    env_file:
      - /opt/novatech-solutions/despliegue/.env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    networks:
      - lavapro_network
  
  frontend:
    container_name: lavapro-frontend
    restart: always
    build:
      context: /home/ubuntu/frontend 
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:80"
    networks:
      - lavapro_network  

networks:
  lavapro_network:
    driver: bridge

volumes:
  postgres_data:
